" ### --- {{ ansible_managed }} --- ###

syntax on               " enable syntax highlighting
set nobackup            " don't create pointless backup files; Use VCS instead
set showmatch           " show matching brackets
set ruler               " show line number in bar
filetype on             " enable filetype detection
filetype indent on      " enable filetype-specific indenting
filetype plugin on      " enable filetype-specific plugins
set expandtab           " spaces instead of tabs
set tabstop=2           " 2 spaces for tabs
set shiftwidth=2        " 2 spaces for indentation
set cursorline          " highlight the current line
